### ISSUE TITLE
Sum is wrong and doesnt support column select mode

### ISSUE THREAD

**Issue by derekwallace** [arturcarvalho/code-sum-up#2]
Hi,
If there are multiple numbers on a line it only selects the 1st.
![image](https://user-images.githubusercontent.com/5574230/64010350-80f60480-cb11-11e9-8855-8742a1c7cced.png)

if you use column select mode it doesn work
![image](https://user-images.githubusercontent.com/5574230/64010378-8e12f380-cb11-11e9-9a33-46be28f84d6c.png)

Potentially useful plugin .....

Thx
derek

**Comment by PulsarFX** [comment]
Still an issue

```
Date    Hours  
12.9.    3 + 3    
12.10.            
18.10.   3,5 + 3,5
22.10.   2        
02.11.   2        
05.11.   2        
06.11.   2        
07.11.   2        
09.11.   1        
10.11.   1        
14.11.   6,5 + 3,5

```

The result for all hours is ... 3 :-)

**Comment by arturcarvalho** [comment]
As said on the README: `sum of the first number found on each line selected`. 

I use this to make estimates. If it accounts for the other numbers I can't put `1h: buy 10 eggs`. But feel free to fork it.
